import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 430, height: 932 }, deviceScaleFactor: 2 });
await page.goto("http://localhost:8767/", { waitUntil: "networkidle" });
await page.waitForFunction(() => !document.body.innerText.includes("Setting the type"), { timeout: 20000 }).catch(() => {});
await page.evaluate(() => document.fonts.ready);
await page.waitForTimeout(2000);
await page.screenshot({ path: "/tmp/home.png" });
await page.getByText("Settings", { exact: false }).first().click();
await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/settings.png" });
await page.getByText("Back to the desk").click();
await page.waitForTimeout(1200);
await page.getByText("New game").first().click();
await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/setup.png" });
await page.getByText("Start game").click();
await page.waitForTimeout(2000);
await page.screenshot({ path: "/tmp/game.png" });
console.log("done");
await browser.close();
